jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
  authorizationStrategy: "loggedInUsersCanDoAnything"

jobs:
  - file: /usr/local/configuration/jobs.groovy
