title: lore-fetcher documentation
description: Documentation page for the lore-fetcher project
theme: just-the-docs

url: https://marcelospessoto.github.io/lore-fetcher/

color_scheme: dark

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
